spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
server:
  servlet:
    context-path: /backend-for-frontend
service:
  dns: http://internal-mynavi-sample-alb-private-2110938554.ap-northeast-1.elb.amazonaws.com